import Foundation

class SloganManager {
    static let sloganArray = [    "Yeni bir macera bir tık uzağında!",
                           "Dünyayı keşfetmeye hazır mısın? Koordinatlar seni bekliyor!",
                           "Her yolculuk bilinmeyene bir adım!",
                           "Rastgele yollara çık, unutulmaz anılar biriktir!",
                           "Haydi! Macera dolu bir dünya seni bekliyor!",
                           "Bilinmeyene doğru cesur bir adım at!",
                           "Yeni rotalar, yeni keşifler. Hazır mısın?",
                           "Hayallerine yolculuk başlasın!",
                           "Keşfedilmemiş yerler seni bekliyor!",
                           "Bir adım at, dünyayı keşfet!",
                           "Rastgele git, unutulmaz anılar biriktir!",
                           "Bir sonraki maceranın başlangıç noktası burada!",
                           "Yollar seni bekliyor, yeni rotalar keşfet!",
                           "Dünya büyük, keşfetmeye başla!",
                           "Sınırların ötesine geçmeye hazır mısın?",
                           "Bilinmeyeni keşfet, macerayı yaşa!",
                           "Rastgele bir dünya, sonsuz macera!",
                           "Her yol yeni bir hikaye, seninki nerede başlıyor?",
                           "Büyük keşifler küçük adımlarla başlar!",
                           "Uzaklara git, bilinmeyeni bul!",
                           "Hedefsizlik bazen en iyi hedef olabilir!",
                           "Dönemeci aş, maceraya atıl!",
                           "Bir sonraki durağın bilinmeyenler olsun!",
                           "Rastgele seç, macera başlasın!",
                           "Yeni keşiflere hazır mısın?",
                           "Dünyanın dört bir yanı seni bekliyor!",
                           "Her tıkla yeni bir serüven başlar!",
                           "Hadi, haritayı rastgele çevir ve yola çık!",
                           "Sıradanlıktan uzak, maceraya yakın!",
                           "Yeni yerler, yeni maceralar, yeni sen!",
                           "Bilinmeyene adım at, cesur ol!",
                           "Dünya senin oyun alanın, keşfetmeye başla!",
                           "Rastgele bir dünya, her tıkta yeni bir macera!",
                           "Koordinatlarla kaderini belirle!",
                           "Keşfetmek cesaret ister, sen cesur ol!",
                           "Her yolculuk bir hikaye, seninki şimdi başlıyor!",
                           "Hiç gitmediğin yerler seni çağırıyor!",
                           "Yol seni nereye götürürse, orada macera başlar!",
                           "Bilmediğin yerlere doğru bir adım at!",
                           "Rastgele bir tıklama, unutulmaz bir macera!",
                           "Hadi, dünyayı keşfetmek için bir koordinat seç!",
                           "Keşfedilmemiş köşeler seni bekliyor!",
                           "Sınırları aş, yeni dünyalar bul!",
                           "Her yer, yeni bir maceranın başlangıcı olabilir!",
                           "Dünya senin elinde, rotayı sen çiz!",
                           "Bir sonraki maceran sadece bir tık uzakta!",
                           "Hayal gücünü genişlet, yollar seni bekliyor!",
                           "Bilmediğin yerler, beklenmedik maceralar!",
                           "Yeni keşifler için cesurca yola çık!",
                           "Rastgele bir yer seç, hayatına heyecan kat!"]
}
