import Foundation

class SloganManager {
    static let sloganArray = [    "A new adventure is just a click away!",
                                  "Are you ready to explore the world? The coordinates are waiting for you!",
                                  "Every journey is a step into the unknown!",
                                  "Set off on random paths, collect unforgettable memories!",
                                  "Come on! A world full of adventure is waiting for you!",
                                  "Take a brave step into the unknown!",
                                  "New routes, new discoveries. Are you ready?",
                                  "Let the journey to your dreams begin!",
                                  "Uncharted places are waiting for you!",
                                  "Take a step, explore the world!",
                                  "Go random, collect unforgettable memories!",
                                  "The starting point of your next adventure is here!",
                                  "The roads are waiting for you, discover new routes!",
                                  "The world is big, start exploring!",
                                  "Are you ready to go beyond the limits?",
                                  "Discover the unknown, live the adventure!",
                                  "A random world, endless adventure!",
                                  "Every journey is a new story, where does yours begin?",
                                  "Big discoveries start with small steps!",
                                  "Go far, find the unknown!",
                                  "Sometimes having no destination is the best destination!",
                                  "Round the bend, dive into adventure!",
                                  "Let your next stop be the unknown!",
                                  "Pick randomly, let the adventure begin!",
                                  "Are you ready for new discoveries?",
                                  "The world is waiting for you from every corner!",
                                  "Every click begins a new adventure!",
                                  "Come on, spin the map randomly and hit the road!",
                                  "Far from ordinary, close to adventure!",
                                  "New places, new adventures, a new you!",
                                  "Take a step into the unknown, be brave!",
                                  "The world is your playground, start exploring!",
                                  "A random world, new adventure with every click!",
                                  "Define your destiny with coordinates!",
                                  "Exploration takes courage, be bold!",
                                  "Every journey is a story, yours starts now!",
                                  "Places you've never been are calling you!",
                                  "Wherever the road takes you, adventure begins there!",
                                  "Take a step into places you don't know!",
                                  "A random click, an unforgettable adventure!",
                                  "Come on, choose a coordinate to explore the world!",
                                  "Unexplored corners are waiting for you!",
                                  "Cross the boundaries, discover new worlds!",
                                  "Every place can be the beginning of a new adventure!",
                                  "The world is in your hands, you draw the route!",
                                  "Your next adventure is just a click away!",
                                  "Expand your imagination, the roads are waiting for you!",
                                  "Unknown places, unexpected adventures!",
                                  "Set out boldly for new discoveries!",
                                  "Pick a random place, add excitement to your life!"
    ]
}
